// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD6503_DHl.Models;

namespace SD6503_DHl.Migrations
{
    [DbContext(typeof(DhlDatabaseContext))]
    [Migration("20210923152137_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SD6503_DHl.Models.AccountDetail", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AccountNumber")
                        .HasName("PK__AccountD__BE2ACD6E470FED9A");

                    b.HasIndex("Identifier");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("SD6503_DHl.Models.LoginAccount", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Identifier")
                        .HasName("PK__LoginAcc__821FB0188D7497D4");

                    b.ToTable("LoginAccount");
                });

            modelBuilder.Entity("SD6503_DHl.Models.Transaction", b =>
                {
                    b.Property<string>("TransactionNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FromAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("PaymentAmount")
                        .HasColumnType("float");

                    b.Property<string>("PaymentPeriod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ToAccount")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<double>("TransactionAmount")
                        .HasColumnType("float");

                    b.HasKey("TransactionNumber")
                        .HasName("PK__Transact__95E36B86462D1D3C");

                    b.HasIndex("FromAccount");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("SD6503_DHl.Models.AccountDetail", b =>
                {
                    b.HasOne("SD6503_DHl.Models.LoginAccount", "IdentifierNavigation")
                        .WithMany("AccountDetails")
                        .HasForeignKey("Identifier")
                        .HasConstraintName("FK__AccountDe__Ident__25869641")
                        .IsRequired();

                    b.Navigation("IdentifierNavigation");
                });

            modelBuilder.Entity("SD6503_DHl.Models.Transaction", b =>
                {
                    b.HasOne("SD6503_DHl.Models.AccountDetail", "FromAccountNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("FromAccount")
                        .HasConstraintName("FK__Transacti__FromA__286302EC")
                        .IsRequired();

                    b.Navigation("FromAccountNavigation");
                });

            modelBuilder.Entity("SD6503_DHl.Models.AccountDetail", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("SD6503_DHl.Models.LoginAccount", b =>
                {
                    b.Navigation("AccountDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
